// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_lbltime;
extern lv_obj_t * ui_lbltitle;
extern lv_obj_t * ui_lblwifi;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_card;
extern lv_obj_t * ui_card1;
extern lv_obj_t * ui_card2;
extern lv_obj_t * ui_card3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

