// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_card_card(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_card = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(comp_card[UI_COMP_CARD_LABEL9], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_card[UI_COMP_CARD_PANEL1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(comp_card[UI_COMP_CARD_LABEL1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(comp_card[UI_COMP_CARD_LBLTEMP], LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(comp_card[UI_COMP_CARD_LABEL9], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(comp_card[UI_COMP_CARD_PANEL1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(comp_card[UI_COMP_CARD_LABEL1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(comp_card[UI_COMP_CARD_LBLTEMP], LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// COMPONENT card

lv_obj_t * ui_card_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_card;
    cui_card = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_card, 180);
    lv_obj_set_height(cui_card, 140);
    lv_obj_set_x(cui_card, -301);
    lv_obj_set_y(cui_card, -100);
    lv_obj_add_flag(cui_card, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(cui_card, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_card, lv_color_hex(0x1A1F3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_card, 178, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_card, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_card, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_card, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_card, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_card, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_card, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(cui_card);
    lv_obj_set_width(cui_Panel1, 140);
    lv_obj_set_height(cui_Panel1, 4);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel1, lv_color_hex(0xF59E0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel1, 178, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel1, lv_color_hex(0x374151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label9;
    cui_Label9 = lv_label_create(cui_card);
    lv_obj_set_width(cui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label9, 0);
    lv_obj_set_y(cui_Label9, 15);
    lv_obj_set_align(cui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label9, "temp");
    lv_obj_remove_flag(cui_Label9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(cui_Label9, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lbltemp;
    cui_lbltemp = lv_label_create(cui_card);
    lv_obj_set_width(cui_lbltemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lbltemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lbltemp, 0);
    lv_obj_set_y(cui_lbltemp, 5);
    lv_obj_set_align(cui_lbltemp, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lbltemp, "24");
    lv_obj_remove_flag(cui_lbltemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(cui_lbltemp, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_lbltemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_lbltemp, lv_color_hex(0xE5E7EB), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(cui_lbltemp, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(cui_lbltemp, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_card);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, 0);
    lv_obj_set_y(cui_Label1, -15);
    lv_obj_set_align(cui_Label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_Label1, "°C");
    lv_obj_remove_flag(cui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xF59E0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CARD_NUM);
    children[UI_COMP_CARD_CARD] = cui_card;
    children[UI_COMP_CARD_PANEL1] = cui_Panel1;
    children[UI_COMP_CARD_LABEL9] = cui_Label9;
    children[UI_COMP_CARD_LBLTEMP] = cui_lbltemp;
    children[UI_COMP_CARD_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_card, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_card, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_card, ui_event_comp_card_card, LV_EVENT_ALL, children);
    ui_comp_card_create_hook(cui_card);
    return cui_card;
}

