// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_CARD_H
#define _UI_COMP_CARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT card
#define UI_COMP_CARD_CARD 0
#define UI_COMP_CARD_PANEL1 1
#define UI_COMP_CARD_LABEL9 2
#define UI_COMP_CARD_LBLTEMP 3
#define UI_COMP_CARD_LABEL1 4
#define _UI_COMP_CARD_NUM 5
lv_obj_t * ui_card_create(lv_obj_t * comp_parent);
void ui_event_comp_card_card(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
